primeira = int(input("Digite a primeira nota: "))
segunda = int(input("Digite a segunda nota: "))
terceira = int(input("Digite a terceira nota: "))
quarta = int(input("Digite a quarta nota: "))
print("A média aritmética é",(primeira+segunda+terceira+quarta)/4)